// <auto-generated />
using System;
using Fanush.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fanush.Migrations
{
    [DbContext(typeof(FanushDbContext))]
    [Migration("20240817080659_SeedDataAndFeatures2")]
    partial class SeedDataAndFeatures2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.DevelopmentPlan", b =>
                {
                    b.Property<int>("DevelopmentPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevelopmentPlanId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DevelopmentPlanId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GoalId");

                    b.ToTable("DevelopmentPlans");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoalId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.PerformanceReport", b =>
                {
                    b.Property<int>("PerformanceReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceReportId"));

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionItems")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreasForImprovement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int");

                    b.Property<string>("GoalsMet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformanceScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerformanceReportId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PerformanceReports");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.PerformanceReview", b =>
                {
                    b.Property<int>("PerformanceReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceReviewId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("PerformanceReviewId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PerformanceReviews");
                });

            modelBuilder.Entity("Fanush.Entities.RecruitmentManagement.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpectedSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedinProfileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicantId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Fanush.Entities.RecruitmentManagement.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterviewType")
                        .HasColumnType("int");

                    b.Property<string>("Interviewer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterviewId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("Fanush.Entities.RecruitmentManagement.JobPosting", b =>
                {
                    b.Property<int>("JobPostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobPostingId"));

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("BenefitsOffered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoteWork")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobPostingId");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.AbsenceReport", b =>
                {
                    b.Property<int>("AbsenceReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbsenceReportId"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HalfDayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbsenceReportId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AbsenceReports");

                    b.HasData(
                        new
                        {
                            AbsenceReportId = 1,
                            ApprovedDate = new DateTime(2024, 8, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver = "John Doe",
                            EmployeeId = 1,
                            EndDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHalfDay = false,
                            IsPaid = true,
                            Reason = "Medical Leave",
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            AbsenceReportId = 2,
                            Approver = "Jane Smith",
                            EmployeeId = 2,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HalfDayType = "Morning",
                            IsHalfDay = true,
                            IsPaid = false,
                            Reason = "Personal Leave",
                            StartDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            AbsenceReportId = 3,
                            ApprovedDate = new DateTime(2024, 8, 14, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Approver = "Emily Brown",
                            EmployeeId = 3,
                            EndDate = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHalfDay = false,
                            IsPaid = true,
                            Reason = "Vacation",
                            StartDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            AbsenceReportId = 4,
                            ApprovedDate = new DateTime(2024, 8, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver = "Chris Evans",
                            EmployeeId = 4,
                            EndDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HalfDayType = "Afternoon",
                            IsHalfDay = true,
                            IsPaid = true,
                            Reason = "Medical Appointment",
                            StartDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            AbsenceReportId = 5,
                            Approver = "Anna Taylor",
                            EmployeeId = 5,
                            EndDate = new DateTime(2024, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHalfDay = false,
                            IsPaid = false,
                            Reason = "Family Emergency",
                            StartDate = new DateTime(2024, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            AbsenceReportId = 6,
                            ApprovedDate = new DateTime(2024, 8, 24, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver = "Robert Downey",
                            EmployeeId = 6,
                            EndDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HalfDayType = "Morning",
                            IsHalfDay = true,
                            IsPaid = true,
                            Reason = "Childcare",
                            StartDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            AbsenceReportId = 7,
                            ApprovedDate = new DateTime(2024, 8, 27, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Approver = "Scarlett Johansson",
                            EmployeeId = 7,
                            EndDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HalfDayType = "Afternoon",
                            IsHalfDay = true,
                            IsPaid = false,
                            Reason = "Study Leave",
                            StartDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            AbsenceReportId = 8,
                            ApprovedDate = new DateTime(2024, 8, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Approver = "Mark Ruffalo",
                            EmployeeId = 8,
                            EndDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHalfDay = false,
                            IsPaid = true,
                            Reason = "Holiday",
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        },
                        new
                        {
                            AbsenceReportId = 9,
                            Approver = "Natalie Portman",
                            EmployeeId = 9,
                            EndDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HalfDayType = "Morning",
                            IsHalfDay = true,
                            IsPaid = false,
                            Reason = "Sick Leave",
                            StartDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            AbsenceReportId = 10,
                            ApprovedDate = new DateTime(2024, 9, 9, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Approver = "Chris Hemsworth",
                            EmployeeId = 10,
                            EndDate = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHalfDay = false,
                            IsPaid = true,
                            Reason = "Workshop Attendance",
                            StartDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.ClockInOut", b =>
                {
                    b.Property<int>("ClockInOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClockInOutId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClockOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EarlyDepartureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEarlyDeparture")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLateArrival")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkday")
                        .HasColumnType("bit");

                    b.Property<string>("LateArrivalReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ClockInOutId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ClockInOuts");

                    b.HasData(
                        new
                        {
                            ClockInOutId = 1,
                            Action = "ClockIn",
                            ApprovedBy = "John Doe",
                            ClockInTime = new DateTime(2024, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = false,
                            IsOvertime = false,
                            IsWorkday = true,
                            LateArrivalReason = "",
                            Location = "Office A",
                            Notes = "Normal day",
                            OvertimeHours = 0m,
                            Timestamp = new DateTime(2024, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 2,
                            Action = "ClockIn",
                            ApprovedBy = "Jane Smith",
                            ClockInTime = new DateTime(2024, 8, 2, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 2, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = true,
                            IsOvertime = true,
                            IsWorkday = true,
                            LateArrivalReason = "Traffic",
                            Location = "Office B",
                            Notes = "Late arrival due to traffic",
                            OvertimeHours = 0.5m,
                            Timestamp = new DateTime(2024, 8, 2, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 3,
                            Action = "ClockIn",
                            ApprovedBy = "Emily Johnson",
                            ClockInTime = new DateTime(2024, 8, 3, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 3, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = false,
                            IsOvertime = false,
                            IsWorkday = true,
                            LateArrivalReason = "",
                            Location = "Remote",
                            Notes = "Working from home",
                            OvertimeHours = 0m,
                            Timestamp = new DateTime(2024, 8, 3, 7, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 4,
                            Action = "ClockIn",
                            ApprovedBy = "Michael Brown",
                            ClockInTime = new DateTime(2024, 8, 4, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 4, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = true,
                            IsOvertime = true,
                            IsWorkday = true,
                            LateArrivalReason = "Doctor's appointment",
                            Location = "Office C",
                            Notes = "Late due to doctor's appointment",
                            OvertimeHours = 0.25m,
                            Timestamp = new DateTime(2024, 8, 4, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 5,
                            Action = "ClockIn",
                            ApprovedBy = "David Wilson",
                            ClockInTime = new DateTime(2024, 8, 5, 7, 55, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 5, 17, 5, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = false,
                            IsOvertime = true,
                            IsWorkday = true,
                            LateArrivalReason = "",
                            Location = "Office A",
                            Notes = "Arrived early",
                            OvertimeHours = 0.17m,
                            Timestamp = new DateTime(2024, 8, 5, 7, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 6,
                            Action = "ClockIn",
                            ApprovedBy = "John Doe",
                            ClockInTime = new DateTime(2024, 8, 6, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 6, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = true,
                            IsOvertime = false,
                            IsWorkday = true,
                            LateArrivalReason = "Family emergency",
                            Location = "Remote",
                            Notes = "Late due to family emergency",
                            OvertimeHours = 0m,
                            Timestamp = new DateTime(2024, 8, 6, 8, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 7,
                            Action = "ClockIn",
                            ApprovedBy = "Jane Smith",
                            ClockInTime = new DateTime(2024, 8, 7, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 7, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = true,
                            IsOvertime = true,
                            IsWorkday = true,
                            LateArrivalReason = "Transport issues",
                            Location = "Office B",
                            Notes = "Slight delay due to transport issues",
                            OvertimeHours = 0.17m,
                            Timestamp = new DateTime(2024, 8, 7, 8, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 8,
                            Action = "ClockIn",
                            ApprovedBy = "Emily Johnson",
                            ClockInTime = new DateTime(2024, 8, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = false,
                            IsOvertime = false,
                            IsWorkday = true,
                            LateArrivalReason = "",
                            Location = "Office C",
                            Notes = "Normal clock-in",
                            OvertimeHours = 0m,
                            Timestamp = new DateTime(2024, 8, 8, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 9,
                            Action = "ClockIn",
                            ApprovedBy = "Michael Brown",
                            ClockInTime = new DateTime(2024, 8, 9, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 9, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = false,
                            IsOvertime = true,
                            IsWorkday = true,
                            LateArrivalReason = "",
                            Location = "Remote",
                            Notes = "Early clock-in",
                            OvertimeHours = 0.17m,
                            Timestamp = new DateTime(2024, 8, 9, 7, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClockInOutId = 10,
                            Action = "ClockIn",
                            ApprovedBy = "David Wilson",
                            ClockInTime = new DateTime(2024, 8, 10, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            ClockOutTime = new DateTime(2024, 8, 10, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 10,
                            IsActive = true,
                            IsEarlyDeparture = false,
                            IsLateArrival = true,
                            IsOvertime = true,
                            IsWorkday = true,
                            LateArrivalReason = "Personal reasons",
                            Location = "Office A",
                            Notes = "Late due to personal reasons",
                            OvertimeHours = 0.17m,
                            Timestamp = new DateTime(2024, 8, 10, 8, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<string>("ApprovalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaidLeave")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("LeaveId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.Overtime", b =>
                {
                    b.Property<int>("OvertimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OvertimeId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OvertimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OvertimeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Overtimes");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.PayrollIntegration", b =>
                {
                    b.Property<int>("PayrollIntegrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollIntegrationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IntegrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntegrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PayPeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PayPeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayrollSystemId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PayrollIntegrationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PayrollIntegrations");
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Engineering",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Human Resources",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Marketing",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Finance",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Operations",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "IT",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Sales",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Customer Service",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 9,
                            DepartmentName = "Research & Development",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 10,
                            DepartmentName = "Legal",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BloodGroup = "O+",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3342),
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "john.doe@example.com",
                            EmergencyContactNumber = "9876543210",
                            FathersName = "James Doe",
                            FirstName = "John",
                            Gender = "Male",
                            IsActive = true,
                            JobTitleId = 1,
                            LastName = "Doe",
                            MaritalStatus = "Married",
                            MothersName = "Anna Doe",
                            NationalId = "1234567890123",
                            Nationality = "American",
                            PassportNumber = "A12345678",
                            PermanentAddress = "abc",
                            PhoneNumber = "1234567890",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/john_doe.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3343)
                        },
                        new
                        {
                            EmployeeId = 2,
                            BloodGroup = "A+",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3350),
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2015, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "jane.smith@example.com",
                            EmergencyContactNumber = "1234567890",
                            FathersName = "Robert Smith",
                            FirstName = "Jane",
                            Gender = "Female",
                            IsActive = true,
                            JobTitleId = 2,
                            LastName = "Smith",
                            MaritalStatus = "Single",
                            MothersName = "Laura Smith",
                            NationalId = "9876543210987",
                            Nationality = "Canadian",
                            PassportNumber = "B23456789",
                            PermanentAddress = "abc",
                            PhoneNumber = "9876543210",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/jane_smith.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3351)
                        },
                        new
                        {
                            EmployeeId = 3,
                            BloodGroup = "B+",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3358),
                            DateOfBirth = new DateTime(1982, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2008, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "michael.johnson@example.com",
                            EmergencyContactNumber = "6666666666",
                            FathersName = "David Johnson",
                            FirstName = "Michael",
                            Gender = "Male",
                            IsActive = true,
                            JobTitleId = 3,
                            LastName = "Johnson",
                            MaritalStatus = "Married",
                            MothersName = "Emily Johnson",
                            NationalId = "5555555555555",
                            Nationality = "British",
                            PassportNumber = "C34567890",
                            PermanentAddress = "abc",
                            PhoneNumber = "5555555555",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/michael_johnson.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3359)
                        },
                        new
                        {
                            EmployeeId = 4,
                            BloodGroup = "AB-",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3364),
                            DateOfBirth = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "emily.brown@example.com",
                            EmergencyContactNumber = "3333333333",
                            FathersName = "William Brown",
                            FirstName = "Emily",
                            Gender = "Female",
                            IsActive = true,
                            JobTitleId = 4,
                            LastName = "Brown",
                            MaritalStatus = "Single",
                            MothersName = "Elizabeth Brown",
                            NationalId = "4444444444444",
                            Nationality = "Australian",
                            PassportNumber = "D45678901",
                            PermanentAddress = "abc",
                            PhoneNumber = "4444444444",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/emily_brown.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3365)
                        },
                        new
                        {
                            EmployeeId = 5,
                            BloodGroup = "O-",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3370),
                            DateOfBirth = new DateTime(1978, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2012, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "david.wilson@example.com",
                            EmergencyContactNumber = "8888888888",
                            FathersName = "Thomas Wilson",
                            FirstName = "David",
                            Gender = "Male",
                            IsActive = true,
                            JobTitleId = 5,
                            LastName = "Wilson",
                            MaritalStatus = "Married",
                            MothersName = "Sophia Wilson",
                            NationalId = "7777777777777",
                            Nationality = "New Zealander",
                            PassportNumber = "E56789012",
                            PermanentAddress = "abc",
                            PhoneNumber = "7777777777",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/david_wilson.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3370)
                        },
                        new
                        {
                            EmployeeId = 6,
                            BloodGroup = "A-",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3376),
                            DateOfBirth = new DateTime(1989, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2016, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 6,
                            Email = "sophia.martinez@example.com",
                            EmergencyContactNumber = "9999999999",
                            FathersName = "Carlos Martinez",
                            FirstName = "Sophia",
                            Gender = "Female",
                            IsActive = true,
                            JobTitleId = 6,
                            LastName = "Martinez",
                            MaritalStatus = "Single",
                            MothersName = "Maria Martinez",
                            NationalId = "2222222222222",
                            Nationality = "Spanish",
                            PassportNumber = "F67890123",
                            PermanentAddress = "abc",
                            PhoneNumber = "2222222222",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/sophia_martinez.jpg",
                            Religion = "Catholic",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3377)
                        },
                        new
                        {
                            EmployeeId = 7,
                            BloodGroup = "B-",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3382),
                            DateOfBirth = new DateTime(1980, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2005, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 7,
                            Email = "daniel.taylor@example.com",
                            EmergencyContactNumber = "1111111111",
                            FathersName = "Henry Taylor",
                            FirstName = "Daniel",
                            Gender = "Male",
                            IsActive = true,
                            JobTitleId = 7,
                            LastName = "Taylor",
                            MaritalStatus = "Married",
                            MothersName = "Alice Taylor",
                            NationalId = "6666666666666",
                            Nationality = "South African",
                            PassportNumber = "G78901234",
                            PermanentAddress = "abc",
                            PhoneNumber = "6666666666",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/daniel_taylor.jpg",
                            Religion = "Jewish",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3383)
                        },
                        new
                        {
                            EmployeeId = 8,
                            BloodGroup = "AB+",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3388),
                            DateOfBirth = new DateTime(1995, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            Email = "olivia.anderson@example.com",
                            EmergencyContactNumber = "7777777777",
                            FathersName = "George Anderson",
                            FirstName = "Olivia",
                            Gender = "Female",
                            IsActive = true,
                            JobTitleId = 8,
                            LastName = "Anderson",
                            MaritalStatus = "Single",
                            MothersName = "Eleanor Anderson",
                            NationalId = "9999999999999",
                            Nationality = "American",
                            PassportNumber = "H89012345",
                            PermanentAddress = "abc",
                            PhoneNumber = "9999999999",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/olivia_anderson.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3388)
                        },
                        new
                        {
                            EmployeeId = 9,
                            BloodGroup = "O+",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3451),
                            DateOfBirth = new DateTime(1987, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2018, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 9,
                            Email = "ethan.thomas@example.com",
                            EmergencyContactNumber = "5555555555",
                            FathersName = "Samuel Thomas",
                            FirstName = "Ethan",
                            Gender = "Male",
                            IsActive = true,
                            JobTitleId = 9,
                            LastName = "Thomas",
                            MaritalStatus = "Married",
                            MothersName = "Lily Thomas",
                            NationalId = "3333333333333",
                            Nationality = "Indian",
                            PassportNumber = "I90123456",
                            PermanentAddress = "abc",
                            PhoneNumber = "3333333333",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/ethan_thomas.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3451)
                        },
                        new
                        {
                            EmployeeId = 10,
                            BloodGroup = "A+",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3457),
                            DateOfBirth = new DateTime(1991, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2013, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 10,
                            Email = "ava.white@example.com",
                            EmergencyContactNumber = "4444444444",
                            FathersName = "Frank White",
                            FirstName = "Ava",
                            Gender = "Female",
                            IsActive = true,
                            JobTitleId = 10,
                            LastName = "White",
                            MaritalStatus = "Single",
                            MothersName = "Grace White",
                            NationalId = "8888888888888",
                            Nationality = "Canadian",
                            PassportNumber = "J01234567",
                            PermanentAddress = "abc",
                            PhoneNumber = "8888888888",
                            PresentAddress = "abc",
                            ProfileImagePath = "/images/profiles/ava_white.jpg",
                            Religion = "Christian",
                            UpdatedBy = "Admin",
                            UpdatedOn = new DateTime(2024, 8, 17, 8, 6, 57, 626, DateTimeKind.Utc).AddTicks(3457)
                        });
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.EmployeeDataImportExport", b =>
                {
                    b.Property<int>("ImportExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportExportId"));

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportExportDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImportExportId");

                    b.ToTable("EmployeeDataImportExports");

                    b.HasData(
                        new
                        {
                            ImportExportId = 1,
                            FileName = "employees.xlsx",
                            FilePath = "/uploads/employees.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Import"
                        },
                        new
                        {
                            ImportExportId = 2,
                            FileName = "employees_export.xlsx",
                            FilePath = "/exports/employees_export.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Export"
                        },
                        new
                        {
                            ImportExportId = 3,
                            FileName = "employees_backup.xlsx",
                            FilePath = "/backups/employees_backup.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Import"
                        },
                        new
                        {
                            ImportExportId = 4,
                            FileName = "employees_archive.xlsx",
                            FilePath = "/archives/employees_archive.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Export"
                        },
                        new
                        {
                            ImportExportId = 5,
                            FileName = "employees_data.xlsx",
                            FilePath = "/uploads/employees_data.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Import"
                        },
                        new
                        {
                            ImportExportId = 6,
                            FileName = "employees_info.xlsx",
                            FilePath = "/exports/employees_info.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Export"
                        },
                        new
                        {
                            ImportExportId = 7,
                            FileName = "employees_sheet.xlsx",
                            FilePath = "/uploads/employees_sheet.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Import"
                        },
                        new
                        {
                            ImportExportId = 8,
                            FileName = "employees_export_info.xlsx",
                            FilePath = "/exports/employees_export_info.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Export"
                        },
                        new
                        {
                            ImportExportId = 9,
                            FileName = "employees_data_sheet.xlsx",
                            FilePath = "/uploads/employees_data_sheet.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Import"
                        },
                        new
                        {
                            ImportExportId = 10,
                            FileName = "employees_info_backup.xlsx",
                            FilePath = "/exports/employees_info_backup.xlsx",
                            ImportExportDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Type = "Export"
                        });
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.EmployeeLifecycle", b =>
                {
                    b.Property<int>("LifecycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LifecycleId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("LifecycleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeLifecycles");

                    b.HasData(
                        new
                        {
                            LifecycleId = 1,
                            ActionDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 1,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 2,
                            ActionDate = new DateTime(2015, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 2,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 3,
                            ActionDate = new DateTime(2008, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 3,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 4,
                            ActionDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 4,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 5,
                            ActionDate = new DateTime(2012, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 5,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 6,
                            ActionDate = new DateTime(2016, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 6,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 7,
                            ActionDate = new DateTime(2005, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 7,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 8,
                            ActionDate = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 8,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 9,
                            ActionDate = new DateTime(2018, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 9,
                            IsActive = true
                        },
                        new
                        {
                            LifecycleId = 10,
                            ActionDate = new DateTime(2013, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionType = "Onboarding",
                            EmployeeId = 10,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.JobTitle", b =>
                {
                    b.Property<int>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTitleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTitleId");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            JobTitleId = 1,
                            IsActive = true,
                            JobTitleName = "Software Engineer"
                        },
                        new
                        {
                            JobTitleId = 2,
                            IsActive = true,
                            JobTitleName = "HR Manager"
                        },
                        new
                        {
                            JobTitleId = 3,
                            IsActive = true,
                            JobTitleName = "Quality Assurance Analyst"
                        },
                        new
                        {
                            JobTitleId = 4,
                            IsActive = true,
                            JobTitleName = "Marketing Specialist"
                        },
                        new
                        {
                            JobTitleId = 5,
                            IsActive = true,
                            JobTitleName = "Finance Manager"
                        },
                        new
                        {
                            JobTitleId = 6,
                            IsActive = true,
                            JobTitleName = "Operations Coordinator"
                        },
                        new
                        {
                            JobTitleId = 7,
                            IsActive = true,
                            JobTitleName = "IT Support Specialist"
                        },
                        new
                        {
                            JobTitleId = 8,
                            IsActive = true,
                            JobTitleName = "Sales Representative"
                        },
                        new
                        {
                            JobTitleId = 9,
                            IsActive = true,
                            JobTitleName = "Customer Service Representative"
                        },
                        new
                        {
                            JobTitleId = 10,
                            IsActive = true,
                            JobTitleName = "Project Manager"
                        });
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.DevelopmentPlan", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("DevelopmentPlans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fanush.Entities.PerformenceManagement.Goal", "Goal")
                        .WithMany("DevelopmentPlans")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.Goal", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("Goals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.PerformanceReport", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.PerformanceReview", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("PerformanceReviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.RecruitmentManagement.Applicant", b =>
                {
                    b.OwnsOne("Fanush.Entities.RecruitmentManagement.Applicant+Educations", "Education", b1 =>
                        {
                            b1.Property<int>("ApplicantId")
                                .HasColumnType("int");

                            b1.Property<string>("Degree")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Institution")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PassingYear")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Result")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsOne("Fanush.Entities.RecruitmentManagement.Applicant+WorkExperiences", "WorkExperience", b1 =>
                        {
                            b1.Property<int>("ApplicantId")
                                .HasColumnType("int");

                            b1.Property<string>("Company")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Duration")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.Navigation("Education")
                        .IsRequired();

                    b.Navigation("WorkExperience")
                        .IsRequired();
                });

            modelBuilder.Entity("Fanush.Entities.RecruitmentManagement.Interview", b =>
                {
                    b.HasOne("Fanush.Entities.RecruitmentManagement.Applicant", "Applicant")
                        .WithMany("ApplicantInterviews")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.AbsenceReport", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("AbsenceReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.ClockInOut", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("ClockInOuts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.Leave", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.Overtime", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("Overtimes")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.TimeAndAttendence.PayrollIntegration", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", null)
                        .WithMany("PayrollIntegrations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.Employee", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fanush.Models.EmployeeManagement.JobTitle", "JobTitle")
                        .WithMany("Employee")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.EmployeeLifecycle", b =>
                {
                    b.HasOne("Fanush.Models.EmployeeManagement.Employee", "Employee")
                        .WithMany("EmployeeLifecycles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Fanush.Entities.PerformenceManagement.Goal", b =>
                {
                    b.Navigation("DevelopmentPlans");
                });

            modelBuilder.Entity("Fanush.Entities.RecruitmentManagement.Applicant", b =>
                {
                    b.Navigation("ApplicantInterviews");
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.Employee", b =>
                {
                    b.Navigation("AbsenceReports");

                    b.Navigation("ClockInOuts");

                    b.Navigation("DevelopmentPlans");

                    b.Navigation("EmployeeLifecycles");

                    b.Navigation("Goals");

                    b.Navigation("Leaves");

                    b.Navigation("Overtimes");

                    b.Navigation("PayrollIntegrations");

                    b.Navigation("PerformanceReports");

                    b.Navigation("PerformanceReviews");
                });

            modelBuilder.Entity("Fanush.Models.EmployeeManagement.JobTitle", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
